source "https://rubygems.org"

ruby "2.3.0"

gem "autoprefixer-rails"
gem "bourbon", "~> 4.2.0"
gem "delayed_job_active_record"
gem 'dotenv-rails'
gem "flutie"
gem "foreman"
gem "haml"
gem "jquery-rails"
gem "neat", "~> 1.7.0"
gem "newrelic_rpm", ">= 3.9.8"
gem "normalize-rails", "~> 3.0.0"
gem "pg"
gem "unicorn"
gem "rack-canonical-host"
gem "rails", "~> 4.2.5.2"
gem "recipient_interceptor"
gem "sass-rails", "~> 5.0"
gem "simple_form"
gem "sprockets", ">= 3.0.0"
gem "sprockets-es6"
gem "title"
gem "uglifier"

group :development do
  gem "quiet_assets"
  gem "refills"
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
  gem 'capistrano', '~> 3.2.0'
  gem 'capistrano-bundler', '~> 1.1.4'
  gem 'capistrano-foreman'
  gem 'capistrano-nginx-unicorn'
  gem 'capistrano-rails', '~> 1.1.3'
  gem 'capistrano-rbenv'
  gem 'capistrano3-postgres', require: false
  gem 'capistrano3-unicorn'
end

group :development, :test do
  gem "awesome_print"
  gem "bullet"
  gem "bundler-audit", ">= 0.5.0", require: false
  gem "factory_girl_rails"
  gem 'guard-rspec', require: false
  gem "rubocop"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.4.0"
end

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

group :test do
  gem "capybara-webkit"
  gem "database_cleaner"
  gem "formulaic"
  gem "launchy"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "timecop"
  gem "webmock"
end

group :staging, :production do
  gem "rack-timeout"
end
