# Capfile
require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rbenv"
require "capistrano/bundler"
require "capistrano/rails/assets"
require "capistrano/rails/migrations"
require "capistrano/foreman"
require "capistrano3/postgres"
# Only use this to generate nginx config
# require "capistrano/nginx_unicorn"

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
